#cloud-config

---
hostname: VM_HOST 
users:
  - name: core
    passwd: PASSWD 
    groups:
      - sudo
      - docker
  - name: root
    passwd: PASSWD 
coreos:
  units:
    - name: etcd.service
      mask: true
    - name: setup-network-environment.service
      command: start
      content: |
        [Unit]
        Description=Setup networking environment
        Documentation=https://github.com/kelseyhightower/setup-network-environment
        Requires=network-online.target
        After=network-online.target

        [Service]
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStartPre=-/usr/bin/wget -N -P /opt/bin https://github.com/kelseyhightower/setup-network-environment/releases/download/v1.0.0/setup-network-environment
        ExecStartPre=/usr/bin/chmod +x /opt/bin/setup-network-environment
        ExecStart=/opt/bin/setup-network-environment
        RemainAfterExit=yes
        Type=oneshot
    - name: fleet.service
      command: start
      content: |
        [Unit]
        Description=fleet daemon
        Wants=fleet.socket
        After=fleet.socket

        [Service]
        Environment="FLEET_ETCD_SERVERS=http://ETCD_HOST:4001"
        Environment="FLEET_METADATA=role=node"
        ExecStart=/usr/bin/fleetd
        Restart=always
        RestartSec=10s
    - name: docker.service
      command: start
